"""Initial migration

Revision ID: 97bf2a54fe6e
Revises: 0cd434b61064
Create Date: 2024-09-24 20:33:37.468598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97bf2a54fe6e'
down_revision = '0cd434b61064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.alter_column('ranking',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.alter_column('ranking',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
